name: Prepare environment
description: "Reusable step for preparing environment"
inputs:
    install-dependencies:
        description: "Whether to install dependencies"
        required: false
        default: true

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v6
        - name: Install dependencies
          if: ${{ inputs.install-dependencies }}
          run: |
              npm install -g pnpm
              pnpm install --frozen-lockfile
          shell: bash
